# Generated by Django 4.1.5 on 2023-01-29 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0003_alter_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.paymenttype'),
            preserve_default=False,
        ),
    ]
