# Generated by Django 4.1.5 on 2023-02-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0004_order_payment_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order', through='bangazonapi.OrderProducts', to='bangazonapi.product'),
        ),
    ]
